// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: voucher_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	VoucherService_StoreOrderDetails_FullMethodName    = "/VoucherService/StoreOrderDetails"
	VoucherService_RetrieveOrderDetails_FullMethodName = "/VoucherService/RetrieveOrderDetails"
	VoucherService_GetAllOrders_FullMethodName         = "/VoucherService/GetAllOrders"
)

// VoucherServiceClient is the client API for VoucherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VoucherServiceClient interface {
	StoreOrderDetails(ctx context.Context, in *StoreOrderDetailsRequest, opts ...grpc.CallOption) (*StoreOrderDetailsResponse, error)
	RetrieveOrderDetails(ctx context.Context, in *RetrieveOrderDetailsRequest, opts ...grpc.CallOption) (*RetrieveOrderDetailsResponse, error)
	GetAllOrders(ctx context.Context, in *GetAllOrdersRequest, opts ...grpc.CallOption) (*GetAllOrdersResponse, error)
}

type voucherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVoucherServiceClient(cc grpc.ClientConnInterface) VoucherServiceClient {
	return &voucherServiceClient{cc}
}

func (c *voucherServiceClient) StoreOrderDetails(ctx context.Context, in *StoreOrderDetailsRequest, opts ...grpc.CallOption) (*StoreOrderDetailsResponse, error) {
	out := new(StoreOrderDetailsResponse)
	err := c.cc.Invoke(ctx, VoucherService_StoreOrderDetails_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voucherServiceClient) RetrieveOrderDetails(ctx context.Context, in *RetrieveOrderDetailsRequest, opts ...grpc.CallOption) (*RetrieveOrderDetailsResponse, error) {
	out := new(RetrieveOrderDetailsResponse)
	err := c.cc.Invoke(ctx, VoucherService_RetrieveOrderDetails_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voucherServiceClient) GetAllOrders(ctx context.Context, in *GetAllOrdersRequest, opts ...grpc.CallOption) (*GetAllOrdersResponse, error) {
	out := new(GetAllOrdersResponse)
	err := c.cc.Invoke(ctx, VoucherService_GetAllOrders_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VoucherServiceServer is the server API for VoucherService service.
// All implementations must embed UnimplementedVoucherServiceServer
// for forward compatibility
type VoucherServiceServer interface {
	StoreOrderDetails(context.Context, *StoreOrderDetailsRequest) (*StoreOrderDetailsResponse, error)
	RetrieveOrderDetails(context.Context, *RetrieveOrderDetailsRequest) (*RetrieveOrderDetailsResponse, error)
	GetAllOrders(context.Context, *GetAllOrdersRequest) (*GetAllOrdersResponse, error)
	mustEmbedUnimplementedVoucherServiceServer()
}

// UnimplementedVoucherServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVoucherServiceServer struct {
}

func (UnimplementedVoucherServiceServer) StoreOrderDetails(context.Context, *StoreOrderDetailsRequest) (*StoreOrderDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreOrderDetails not implemented")
}
func (UnimplementedVoucherServiceServer) RetrieveOrderDetails(context.Context, *RetrieveOrderDetailsRequest) (*RetrieveOrderDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveOrderDetails not implemented")
}
func (UnimplementedVoucherServiceServer) GetAllOrders(context.Context, *GetAllOrdersRequest) (*GetAllOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllOrders not implemented")
}
func (UnimplementedVoucherServiceServer) mustEmbedUnimplementedVoucherServiceServer() {}

// UnsafeVoucherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VoucherServiceServer will
// result in compilation errors.
type UnsafeVoucherServiceServer interface {
	mustEmbedUnimplementedVoucherServiceServer()
}

func RegisterVoucherServiceServer(s grpc.ServiceRegistrar, srv VoucherServiceServer) {
	s.RegisterService(&VoucherService_ServiceDesc, srv)
}

func _VoucherService_StoreOrderDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreOrderDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoucherServiceServer).StoreOrderDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoucherService_StoreOrderDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoucherServiceServer).StoreOrderDetails(ctx, req.(*StoreOrderDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoucherService_RetrieveOrderDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveOrderDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoucherServiceServer).RetrieveOrderDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoucherService_RetrieveOrderDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoucherServiceServer).RetrieveOrderDetails(ctx, req.(*RetrieveOrderDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoucherService_GetAllOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoucherServiceServer).GetAllOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoucherService_GetAllOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoucherServiceServer).GetAllOrders(ctx, req.(*GetAllOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VoucherService_ServiceDesc is the grpc.ServiceDesc for VoucherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VoucherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "VoucherService",
	HandlerType: (*VoucherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreOrderDetails",
			Handler:    _VoucherService_StoreOrderDetails_Handler,
		},
		{
			MethodName: "RetrieveOrderDetails",
			Handler:    _VoucherService_RetrieveOrderDetails_Handler,
		},
		{
			MethodName: "GetAllOrders",
			Handler:    _VoucherService_GetAllOrders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "voucher_service.proto",
}
