version: '3'

services:
  # User Service
  user-service:
    container_name: user-service-container
    build:
      context: .
      dockerfile: back-end/user-service/Dockerfile
    env_file:
      - .env
    ports:
      - "50010:50010"
    depends_on:
      - postgres
    networks:
      - backend
      - postgres-access
    restart: unless-stopped

  # Card Service
  card-service:
    container_name: card-service-container
    build:
      context: .
      dockerfile: back-end/card-service/Dockerfile
    env_file:
      - .env
    ports:
      - "50020:50020"
    depends_on:
      - postgres
      - user-service
    networks:
      - backend
      - postgres-access
    restart: unless-stopped

# food Service
  food-service:
    container_name: food-service-container
    build:
      context: .
      dockerfile: back-end/food-service/Dockerfile
    env_file:
      - .env
    ports:
      - "50030:50030"
    depends_on:
      - postgres
      - card-service
      - user-service
    networks:
      - backend
      - postgres-access
    restart: unless-stopped

# Order Service
  order-service:
    container_name: order-service-container
    build:
      context: .
      dockerfile: back-end/order-service/Dockerfile
    env_file:
      - .env
    ports:
      - "50040:50040"
    depends_on:
      - postgres
      - user-service
      - card-service
      - food-service
      - rabbitmq
    networks:
      - backend
      - postgres-access
    restart: unless-stopped

  # Voucher Service
  voucher-service:
    container_name: voucher-service-container
    build:
      context: .
      dockerfile: back-end/voucher-service/Dockerfile
    env_file:
      - .env
    ports:
      - "50050:50050"
    depends_on:
      - redis-database
      - order-service
    networks:
      - backend
      - redis-access
    restart: unless-stopped

  # Report Service
  report-service:
    container_name: report-service-container
    build:
      context: .
      dockerfile: back-end/report-service/Dockerfile
    env_file:
      - .env
    depends_on:
      - order-service
      - user-service
    networks:
      - backend
    restart: unless-stopped

  # Nginx Service
  nginx:
    container_name: nginx-service-container
    image: nginx:latest
    ports:
      - "5050:5050"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service
      - card-service
      - food-service
      - order-service
      - voucher-service
      - rabbitmq
      - postgres
      - redis-database
    networks:
      - backend
    restart: unless-stopped

  # Postgres Service
  postgres:
    container_name: postgres-service-container
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-access
    restart: unless-stopped

  # Redis Database
  redis-database:
    container_name: redis-database-container
    image: redis:latest
    restart: unless-stopped
    volumes:
      - "redis-data:/data"
      - "./redis.conf:/usr/local/etc/redis/redis.conf"
    command: redis-server /usr/local/etc/redis/redis.conf
    env_file:
      - .env
    ports:
      - "6379:6379"
    hostname: redis-database
    networks:
      - redis-access

  rabbitmq:
    container_name: rabbitmq-service-container
    image: 'rabbitmq:3-management'
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - '${RABBITMQ_PORT}:${RABBITMQ_PORT}'
      - '${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}'
    networks:
      - backend


networks:
  backend:
  redis-access:
  postgres-access:

volumes:
  postgres-data:
  redis-data: