// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: food_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FoodService_GetFoodDetailsByName_FullMethodName     = "/FoodService/GetFoodDetailsByName"
	FoodService_GetSideDishDetailsByName_FullMethodName = "/FoodService/GetSideDishDetailsByName"
)

// FoodServiceClient is the client API for FoodService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FoodServiceClient interface {
	GetFoodDetailsByName(ctx context.Context, in *FoodIdRequest, opts ...grpc.CallOption) (*Food, error)
	GetSideDishDetailsByName(ctx context.Context, in *SideDishIdRequest, opts ...grpc.CallOption) (*SideDish, error)
}

type foodServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFoodServiceClient(cc grpc.ClientConnInterface) FoodServiceClient {
	return &foodServiceClient{cc}
}

func (c *foodServiceClient) GetFoodDetailsByName(ctx context.Context, in *FoodIdRequest, opts ...grpc.CallOption) (*Food, error) {
	out := new(Food)
	err := c.cc.Invoke(ctx, FoodService_GetFoodDetailsByName_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *foodServiceClient) GetSideDishDetailsByName(ctx context.Context, in *SideDishIdRequest, opts ...grpc.CallOption) (*SideDish, error) {
	out := new(SideDish)
	err := c.cc.Invoke(ctx, FoodService_GetSideDishDetailsByName_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FoodServiceServer is the server API for FoodService service.
// All implementations must embed UnimplementedFoodServiceServer
// for forward compatibility
type FoodServiceServer interface {
	GetFoodDetailsByName(context.Context, *FoodIdRequest) (*Food, error)
	GetSideDishDetailsByName(context.Context, *SideDishIdRequest) (*SideDish, error)
	mustEmbedUnimplementedFoodServiceServer()
}

// UnimplementedFoodServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFoodServiceServer struct {
}

func (UnimplementedFoodServiceServer) GetFoodDetailsByName(context.Context, *FoodIdRequest) (*Food, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFoodDetailsByName not implemented")
}
func (UnimplementedFoodServiceServer) GetSideDishDetailsByName(context.Context, *SideDishIdRequest) (*SideDish, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSideDishDetailsByName not implemented")
}
func (UnimplementedFoodServiceServer) mustEmbedUnimplementedFoodServiceServer() {}

// UnsafeFoodServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FoodServiceServer will
// result in compilation errors.
type UnsafeFoodServiceServer interface {
	mustEmbedUnimplementedFoodServiceServer()
}

func RegisterFoodServiceServer(s grpc.ServiceRegistrar, srv FoodServiceServer) {
	s.RegisterService(&FoodService_ServiceDesc, srv)
}

func _FoodService_GetFoodDetailsByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FoodIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoodServiceServer).GetFoodDetailsByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FoodService_GetFoodDetailsByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoodServiceServer).GetFoodDetailsByName(ctx, req.(*FoodIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FoodService_GetSideDishDetailsByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SideDishIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoodServiceServer).GetSideDishDetailsByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FoodService_GetSideDishDetailsByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoodServiceServer).GetSideDishDetailsByName(ctx, req.(*SideDishIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FoodService_ServiceDesc is the grpc.ServiceDesc for FoodService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FoodService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FoodService",
	HandlerType: (*FoodServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFoodDetailsByName",
			Handler:    _FoodService_GetFoodDetailsByName_Handler,
		},
		{
			MethodName: "GetSideDishDetailsByName",
			Handler:    _FoodService_GetSideDishDetailsByName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "food_service.proto",
}
