// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: card_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message to get card information
type GetCardInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JwtToken string `protobuf:"bytes,1,opt,name=jwt_token,json=jwtToken,proto3" json:"jwt_token,omitempty"`
}

func (x *GetCardInfoRequest) Reset() {
	*x = GetCardInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_card_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCardInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardInfoRequest) ProtoMessage() {}

func (x *GetCardInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardInfoRequest.ProtoReflect.Descriptor instead.
func (*GetCardInfoRequest) Descriptor() ([]byte, []int) {
	return file_card_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetCardInfoRequest) GetJwtToken() string {
	if x != nil {
		return x.JwtToken
	}
	return ""
}

// Response message containing card information
type CardInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlackListed bool   `protobuf:"varint,1,opt,name=black_listed,json=blackListed,proto3" json:"black_listed,omitempty"`
	Verified    bool   `protobuf:"varint,2,opt,name=verified,proto3" json:"verified,omitempty"`
	AccessLevel int32  `protobuf:"varint,3,opt,name=access_level,json=accessLevel,proto3" json:"access_level,omitempty"`
	Error       string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CardInfoResponse) Reset() {
	*x = CardInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_card_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CardInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardInfoResponse) ProtoMessage() {}

func (x *CardInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_card_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardInfoResponse.ProtoReflect.Descriptor instead.
func (*CardInfoResponse) Descriptor() ([]byte, []int) {
	return file_card_service_proto_rawDescGZIP(), []int{1}
}

func (x *CardInfoResponse) GetBlackListed() bool {
	if x != nil {
		return x.BlackListed
	}
	return false
}

func (x *CardInfoResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *CardInfoResponse) GetAccessLevel() int32 {
	if x != nil {
		return x.AccessLevel
	}
	return 0
}

func (x *CardInfoResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Request message to update reserves count
type UpdateReservesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JwtToken       string `protobuf:"bytes,1,opt,name=jwt_token,json=jwtToken,proto3" json:"jwt_token,omitempty"`
	ReservesChange int32  `protobuf:"varint,2,opt,name=reserves_change,json=reservesChange,proto3" json:"reserves_change,omitempty"` // Positive or negative number to increase or decrease reserves
}

func (x *UpdateReservesRequest) Reset() {
	*x = UpdateReservesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_card_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateReservesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReservesRequest) ProtoMessage() {}

func (x *UpdateReservesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReservesRequest.ProtoReflect.Descriptor instead.
func (*UpdateReservesRequest) Descriptor() ([]byte, []int) {
	return file_card_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateReservesRequest) GetJwtToken() string {
	if x != nil {
		return x.JwtToken
	}
	return ""
}

func (x *UpdateReservesRequest) GetReservesChange() int32 {
	if x != nil {
		return x.ReservesChange
	}
	return 0
}

var File_card_service_proto protoreflect.FileDescriptor

var file_card_service_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x31, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6a, 0x77, 0x74, 0x5f, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6a, 0x77, 0x74, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x8a, 0x01, 0x0a, 0x10, 0x43, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x62, 0x6c, 0x61,
	0x63, 0x6b, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0b, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08,
	0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b,
	0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0x5d, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6a, 0x77,
	0x74, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6a,
	0x77, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x73, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0e, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x32, 0x86, 0x01, 0x0a, 0x0b, 0x43, 0x61, 0x72, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x35, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x13, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x73, 0x12, 0x16, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x46, 0x5a, 0x44, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x69, 0x6d, 0x62, 0x6f, 0x6c, 0x69, 0x73,
	0x6d, 0x2f, 0x73, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x2d, 0x72, 0x65, 0x73, 0x74, 0x61,
	0x75, 0x72, 0x61, 0x6e, 0x74, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x2d, 0x65, 0x6e, 0x64, 0x2f, 0x63,
	0x61, 0x72, 0x64, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_card_service_proto_rawDescOnce sync.Once
	file_card_service_proto_rawDescData = file_card_service_proto_rawDesc
)

func file_card_service_proto_rawDescGZIP() []byte {
	file_card_service_proto_rawDescOnce.Do(func() {
		file_card_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_card_service_proto_rawDescData)
	})
	return file_card_service_proto_rawDescData
}

var file_card_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_card_service_proto_goTypes = []interface{}{
	(*GetCardInfoRequest)(nil),    // 0: GetCardInfoRequest
	(*CardInfoResponse)(nil),      // 1: CardInfoResponse
	(*UpdateReservesRequest)(nil), // 2: UpdateReservesRequest
	(*emptypb.Empty)(nil),         // 3: google.protobuf.Empty
}
var file_card_service_proto_depIdxs = []int32{
	0, // 0: CardService.GetCardInfo:input_type -> GetCardInfoRequest
	2, // 1: CardService.UpdateReserves:input_type -> UpdateReservesRequest
	1, // 2: CardService.GetCardInfo:output_type -> CardInfoResponse
	3, // 3: CardService.UpdateReserves:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_card_service_proto_init() }
func file_card_service_proto_init() {
	if File_card_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_card_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCardInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_card_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CardInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_card_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateReservesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_card_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_card_service_proto_goTypes,
		DependencyIndexes: file_card_service_proto_depIdxs,
		MessageInfos:      file_card_service_proto_msgTypes,
	}.Build()
	File_card_service_proto = out.File
	file_card_service_proto_rawDesc = nil
	file_card_service_proto_goTypes = nil
	file_card_service_proto_depIdxs = nil
}
